language: node_js
node_js: node
services:
- mongodb
env:
    global:
        - CXX=g++-5
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
deploy:
  provider: heroku
  api_key:
    secure: QhG7iQHByLUVZu0vC3iKugJlqtCj0fEU6MlFV7E17QLSYX9yeTKVUQ14x8q4TitOSdakx13FPGhHESJ+64qD9cgaRoeWsjns8ybkM1qJ6x6/qOP/S5rzjBNCgPtOPBCuPr3Miisq5ZK+Eg/wQHyn3FZ2zjFPT3lw0nmCfJN46xois4Wmgqs12JgKEGdQ2rnnyKYsZHa7mGTsTznkZbxg/gcL2PD4qXNWagyZ89RJ5ojEzDk4tMEwK1kCMqelGJvEKIM//zOMlAVyzDXjwbN8UTNfxw4fSuJggK5dxHxVR1ynM5VB7Dn0J8YaJ6MEN6/YfLSHEMkI2DLkgd429msxPFQ/CgZE2KNZ6sw7Smi190iLZVKIk8XboAQW3bV9GdzRSQnDRvxmlLUCSN/COheBA+mAuZb3PcOs9vWc/zKD2Cox4aKMlkRd38NcFqLEB+gGZpQYQSnivq5D7z7J69HWpW83WNaRZRXuHjQKRjH3yf0UWKKt+hvcFnePzhi2/AUpeNKJsYywfdyt680uPE808+EAweiXFKmL13BIheqrvXTNbC2jpDVv5IqrAYOefoxUm77qec18dOfACzaNxDVWUXdWJe3IwZrA8BnJd5MbuHxXzrtBRRJbH5MyXiYDgqmQ5vlNNUrxMagONXBh68Fd7h+DYZ/8aHdYa2ErgQ+Q8T0=
  app: ibill
  on:
    repo: nnh242/ibill
